### ISSUE TITLE
Reture a large set of data from database Async

### ISSUE THREAD

**Issue by cheanney** [oracle/python-cx_Oracle#106]
How do you using cx_Oracle to return batch of rows (Async)?
I am trying to develop a websocket server to return rows using tornado, but the setting data part is blocking the process.
Following is my script:

```python
import time
import random
import random
import json
import datetime
import os
import sys
import cx_Oracle
import string
import re
import subprocess
import asyncio
from tornado import websocket, web, ioloop, escape
from datetime import timedelta
from random import randint
from pprint import pprint
from tornado.web import RequestHandler



os.environ['ORACLE_HOME'] = 'pathToOracleHome'
os.environ['LD_LIBRARY_PATH'] = "$ORACLE_HOME/lib"


def is_hex(a):
    printable = set(string.printable) - set("\x0b\x0c")
    return any(c not in printable for c in a)
def json_print(d):
    print(json.dumps(d, indent=4))
def printf (format,*args):
    sys.stdout.write (format % args)
def db(database_name='localhost/database'):
    return cx_Oracle.connect('user', 'pwd', database_name)
def query_db(query, args=(), one=False):
    cur = db().cursor()
    cur.arraysize = 1500
    cur.execute(query, args)
    return cur

class SummaryWebSocketHandler(websocket.WebSocketHandler):
  clients = []  

  def check_origin(self, origin):
      return True

  def on_message(self, message): 
      print ('message received')

  def closeDbConn(self,cur):
      cur.connection.close()

  def query(self, sql):
      cursor = query_db(sql)
      self.send_data(cursor)

  ### THIS IS THE LONG PROCESS ###
  def send_data(self, cur):
      results = {}
      columns = [column[0] for column in cur.description]
      total = 0
      while True:
          Res = []
          rows = cur.fetchmany()
          if rows == []:
              print('no more rows')
              break;
          for row in rows:
              results = {}
              for i, value in enumerate(row):
                  if value == None:
                      value = '-'
                  results[cur.description[i][0]] = value
              Res.append(results)
          self.write_message(json.dumps(Res))
          total =  total + len(rows)
          print('total rows send', total)
      self.write_message("finished sending all data")
      self.on_close(cur)

  def open(self, table):
      print ('Connection established. \n')
      print ('Query string '+table+'\n')
      p = re.compile(r'fields=')
      m  = p.match(table)
      matches = table.split("&")
      print (matches) 

      param_string = ''
      params = []
      if matches:
      for m in matches:
            print('m', m);
            param = ''
            items = m.split('=')
            if items[1] != '':
                param = '--'+items[0]+' '+items[1]
                params.append(param)
      param_string =  " ".join(params) 

      script = "php getStmt.php "+param_string

      print (script)
      proc = subprocess.Popen(script, shell=True,stdout=subprocess.PIPE)
      sql = proc.stdout.read()
      print (sql)
      self.query(sql)

  def on_close(self, cursor):
      print ('Connection closed.')
      cursor.close()

settings = {'auto_reload': True, 'debug': True}
if __name__ == "__main__":
   print ("Starting websocket server program. Awaiting client requests to open websocket ...")
   application = web.Application([(r"/\/table\/(.*)",SummaryWebSocketHandler), 
                            ]
                            ,**settings)
   application.listen(3001)
   ioloop.IOLoop.instance().start()
```

**Comment by anthony-tuininga** [comment]
What exactly did you want to have happen? Can you provide a bit more information?

**Comment by cheanney** [comment]
I am trying to return a large set of data by smaller batches. Send_data step is blocking the event loop, as a result, new clients can't connect.

Is there any way to run send_data in asyn fashion?

Please refer to this stackoverflow thread: https://stackoverflow.com/questions/46979369/only-one-user-can-connect-to-websocket-server-with-tornado-at-a-time

**Comment by anthony-tuininga** [comment]
If you don't want to block you'll need to use a separate thread to retrieve the data from the database. That should work as expected, though. Have you already tried that?

**Comment by cheanney** [comment]
No, I have not try that yet. I am very new on this. would you mind show me
an example?

Thanks!!

**Comment by anthony-tuininga** [comment]
The module you want to examine is the [threading](https://docs.python.org/3/library/threading.html) module. Something like this is what you want to do:

```python
thread = threading.Thread(target = MyFunction, args = (arg1, arg2, arg3))
thread.start()
```

If you go this route, also make sure that you are enabling threaded mode when you create your connection, as in:

`conn = cx_Oracle.connect("user/pw@tns", threaded=True)`

That should get you started!

**Comment by cjbj** [comment]
Also check https://github.com/oracle/python-cx_Oracle/blob/master/samples/Threads.py and search for 'thread' in https://github.com/oracle/python-cx_Oracle/blob/master/samples/tutorial/Python-and-Oracle-Database-12c-Scripting-for-the-Future.html

**Comment by cheanney** [comment]
@anthony-tuininga and @cjbj 
Thank you for all your help. I will give it a try and will let you guys know the outcomes 
:)

**Comment by anthony-tuininga** [comment]
You're welcome. I'll close this for now but feel free to comment further or re-open if needed.

**Comment by PingPongBalls** [comment]
@anthony-tuininga and @cjbj, I got the following code and got error.

wondering what is your way to handle the return value back to the Tornado?

Thanks so much. :)

```
import tornado.web
from tornado import gen
import json
from tornado.escape import _unicode
from datetime import datetime
from bson import json_util
import cx_Oracle
import threading

class FacilityHandler(ApiBaseHandler):

    def runRabbit(self, sql):
        cur = self.application.oracle_db.cursor()
        cur.execute(sql)
        result = cur.fetchall()
        req.write( result )
        cur.close()
        req.finish()

    @tornado.web.asynchronous
    @gen.coroutine
    def get(self, tech_type, facility_id):           
        result = None
        try:
            facilities = ()
            sql = """string""".format(facilities)

            # print(sql)
            # cursor.execute(sql)
            # rows = cursor.fetchall()
            # self.write_with_formatting( rows )

            thread = threading.Thread(target = self.runRabbit, args = (sql))
            thread.start()

        except Exception as e:
            raise
        finally:
            # cursor.close()
            pass
```

and i got the following error:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/mozart/opt/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/mozart/opt/anaconda/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mozart/run/api/impacts/facility_handler.py", line 37, in runRabbit
    req.write( result )
  File "/home/mozart/opt/anaconda/lib/python3.5/site-packages/tornado/web.py", line 685, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()
```

**Comment by anthony-tuininga** [comment]
I don't know Tornado so can't be certain, but I suspect you can't simply start a thread to perform your processing. Once the get() routine finishes, tornado code probably "finishes" the request on your behalf.

**Comment by PingPongBalls** [comment]
@anthony-tuininga Wow, thanks so much for the quick response!

Found the way out of this, and you are right. it has to be joined back to the Tornado ioloop. 

Cheers

```
    def run_rabbit(self, req, sql, callback):
        cur = req.application.oracle_db.cursor()
        cur.execute(sql)
        result = cur.fetchall()
        cur.close()
        tornado.ioloop.IOLoop.instance().add_callback(functools.partial(callback, result))

    def calculator_callback(self, result):
        self.write_with_formatting( result )
        self.finish()
```
