### ISSUE TITLE
django.db.utils.DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

### ISSUE THREAD

**Issue by gshockbu** [oracle/python-cx_Oracle#151]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64 BIT

2. What is your version of cx_Oracle?
6.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Obtained from Oracle V10.1 as a .zip AMD64

4. What is your version of the Oracle Database?
12.1

5. What is your OS and version?
Ubuntu 16.04

Linux ip-10-57-248-8 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

7. What environment variables did you set?  How *exactly* did you set them?
ORACLE_HOME=/home/webteam/instantclient10_1
LD_LIBRARY_PATH=/home/webteam/instantclient10_1

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

running inside of an sourced django env ...

python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feeb98357b8>
Traceback (most recent call last):
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/oracle/base.py", line 216, in get_new_connection
    return Database.connect(conn_string, **conn_params)
cx_Oracle.DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check_migrations()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/core/management/base.py", line 437, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/webteam/environments/my_env/lib/python3.5/site-packages/django/db/backends/oracle/base.py", line 216, in get_new_connection
    return Database.connect(conn_string, **conn_params)
django.db.utils.DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

9. What error(s) you are seeing?
django.db.utils.DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

**Comment by gshockbu** [comment]
Ok – I’m using Ubuntu, that specific one was called out by Oracle. Should I use a generic Linux_AMD64?

**Comment by cjbj** [comment]
It's not the version of Linux or the distro (though that can affect official support of the Oracle client library stack), but the version of the Oracle client libraries that matters.  Since your DB is 12.1, I'd recommend getting the 12.2 (the current latest) version of Instant Client.

**Comment by gshockbu** [comment]
Cool. I’ll give that a go and report back. 

 

Thank you!

**Comment by gshockbu** [comment]
This recommendation fixed the issue! Thank you.
