### ISSUE TITLE
Ubuntu 18.04 LTS Django 1.7 version cx_oracle 6.3.1 is failing

### ISSUE THREAD

**Issue by seenureddy** [oracle/python-cx_Oracle#191]
### Django 1.7 version cx_oracle is failing:
```
local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 422, in __init__
    self.cursor.numbersAsStrings = True
AttributeError: 'cx_Oracle.Cursor' object has no attribute 'numbersAsStrings'

```

**Comment by seenureddy** [comment]
@cjbj  I have used the 
* cx_oracle 6.3.1 version. 
* Python 2.7.15 version 64 bit
* gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
* Oracle client: instantclient-basic-linux.x64-12.2.0.1.0.zip. Setup instructions: (http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html#ic_x64_inst)
* Ubuntu 18.04 LTS
* Command causes the error `python manage.py runserver`


**Error code while running the Django server.**
`System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0x7f8567855938>
Traceback (most recent call last):
  File "/.venvs/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/.venvs/env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check_migrations()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 437, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 173, in connect
    self.init_connection_state()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 219, in init_connection_state
    cursor = self.create_cursor()
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 265, in create_cursor
    return FormatStylePlaceholderCursor(self.connection)
  File "/.venvs/env/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 422, in __init__
    self.cursor.numbersAsStrings = True
AttributeError: 'cx_Oracle.Cursor' object has no attribute 'numbersAsStrings'
`

**Comment by anthony-tuininga** [comment]
This is an issue with Django as noted here: https://code.djangoproject.com/ticket/28138. The attribute numbersAsStrings was deprecated in cx_Oracle 5.3 and removed in cx_Oracle 6.0. You will have to either use cx_Oracle 5.3 or upgrade to Django 1.11 (last LTS release to support Python 2.7).
