### ISSUE TITLE
Connection close stale while recycling pool connection

### ISSUE THREAD

**Issue by csuriano23** [oracle/python-cx_Oracle#238]
I am experiencing long periods of stale on customer production environment due to recycling pool parameter. The architecture of the solution is the following:

1. Different concurrent tasks are launched on a job scheduler which has 4 workers. Each worker creates a session pool with SQLAlchemy `create_engine(<connection string>, pool_size=8, max_overflow=0, pool_recycle=3600, pool_timeout=30)`

2. Each task executes a complex workflow, which consists of SELECT queries in cascade;

3. The underlying DB is an Oracle RAC with failover and three available addresses for each of the two failover nodes;

Randomically, during the execution of a task, the pool recycler verify the overcoming of the 3600 timeout and triggers the recycling of the connection. This causes a stale that lasts about 15 minutes (sistematically) after which SQLAlchemy succeeds to close and re-open connection and then continues the execution.

After some analysis the cause seems to be the invokation to `cx_Oracle.Connection.close()`.
The completion of function execution takes almost all the 15 minutes.

This is an excerpt of the logger:
```
[myPID]	YYYY-MM-DD 12:07:59,974	pool.py: 513	INFO	Connection <cx_Oracle.Connection to <my_connection_string>> exceeded timeout; recycling
[myPID]	YYYY-MM-DD 12:07:59,974	pool.py: 248	DEBUG	Closing connection <cx_Oracle.Connection to <my_connection_string>>
[myPID]	YYYY-MM-DD 12:23:28,294	pool.py: 255	ERROR	Exception closing connection <cx_Oracle.Connection to <my_connection_string>>
Traceback (most recent call last):
  File "myEnv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 250, in _close_connection
    self._dialect.do_close(connection)
  File "myEnv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_close
    dbapi_connection.close()
DatabaseError: ORA-25408: can not safely replay call

[myPID]	YYYY-MM-DD 12:23:28,401	pool.py: 538	DEBUG	Created new connection <cx_Oracle.Connection to <my_connection_string>>
[myPID]	YYYY-MM-DD 12:23:28,405	base.py: 487	INFO	BEGIN (implicit)
[myPID]	YYYY-MM-DD 12:23:28,406	base.py: 912	INFO	
                    SELECT XXX
                    FROM YYY
                    WHERE ZZZ
```

Could it be some issue due the old cx_Oracle version (5.2.1) against the Oracle 12c?

#### Answer to general questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit

2. What is your cx_Oracle version?
5.2.1

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`<cx_Oracle.Connection instance>.close()`

4. What error(s) you are seeing?
`DatabaseError: ORA-25408: can not safely replay call``
15 minutes for connection recycling

5. What OS (and version) is Python executing on?
CentOS 6.10

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
Oracle Instant Client 12.1

7. What is your Oracle Database version?
Oracle 12c

**Comment by zzzeek** [comment]
sent over from https://bitbucket.org/zzzeek/sqlalchemy/issues/4368/connection-reset-stale-while-recycling

**Comment by anthony-tuininga** [comment]
Interesting. I'm not familiar with that error message. I'll ask internally and get back to you.

**Comment by cjbj** [comment]
We had a brief, incomplete email discussion about this today, but there were more questions than answers. Until that discussion has something concrete to say, here are some side-comments:
- how are you setting the connection 'events' mode? https://cx-oracle.readthedocs.io/en/latest/module.html#cx_Oracle.Connection
- why are you cycling connections?
- can you use a later cx_Oracle, (6.2 or newer) which avoids unnecessary rollbacks when connections are closed?

**Comment by csuriano23** [comment]
Below the info required:

> * how are you setting the connection 'events' mode? https://cx-oracle.readthedocs.io/en/latest/module.html#cx_Oracle.Connection

I don't set the parameter and SQLAlchemy doesn't allow to set externally, so I think it is defaulted to `events=False`

> * why are you cycling connections?

It is standard configuration of the product. For other Oracle DB configs (other customers installations) it doesn't create this issue. My quick fix is to set SQLAlchemy recycle param to -1, so that pool connections are never recycled

> * can you use a later cx_Oracle, (6.2 or newer) which avoids unnecessary rollbacks when connections are closed?

I currently don't know the impacts of such a migration, but it should be planned

Thank you

**Comment by zzzeek** [comment]
> I don't set the parameter and SQLAlchemy doesn't allow to set externally, so I think it is defaulted to events=False

the cx_oracle dialect should be enhanced to let all parameters through to connect but in the meantime you can do this:
```

from sqlalchemy import create_engine
from sqlalchemy.engine import url as sa_url


def my_create_engine(url):
    import cx_Oracle
    from sqlalchemy.dialects.oracle import cx_oracle
    dialect = cx_oracle.dialect

    (cargs, cparams) = dialect().create_connect_args(sa_url.make_url(url))
    cparams['events'] = True

    def cx_oracle_connect():
        return cx_Oracle.connect(*cargs, **cparams)

    return create_engine(url, creator=cx_oracle_connect)

e = my_create_engine("oracle+cx_oracle://scott:tiger@oracle1120")

c = e.connect()
```

**Comment by zzzeek** [comment]
Sorry I'm a moron, pass connect_args, forget all that stuff:

    e = create_engine("oracle+cx_oracle://scott:tiger@oracle1120", connect_args={"events": True})

**Comment by csuriano23** [comment]
> Sorry I'm a moron, pass connect_args, forget all that stuff:
> 
> ```
> e = create_engine("oracle+cx_oracle://scott:tiger@oracle1120", connect_args={"events": True})
> ```

Thank you, that's great, it can be tried easily

**Comment by cjbj** [comment]
@zzzeek does SQLAlchemy use cx_Oracle's session pool?

**Comment by zzzeek** [comment]
@cjbj the dialect itself does not make any use of the session pool, no, though as above someone can pass options to set that up if they'd like

**Comment by cjbj** [comment]
@zzzeek that's a pity (though not totally uncommon).  Without the session pool it loses a lot of high availability features.

**Comment by cjbj** [comment]
@csuriano23 you may be seeing the effect of a TCP timeout.  In the words of our HA expert "Yes, up to 15 minutes is not unusual.  The wait can be up to the TPC_TIMEOUT value, which sys admins are loathe to change.  (Hence the push to have customers use FAN :)"

So, make sure you set events during connection, and make sure the service is sending FAN (Fast Application Notification) events: use srvctl to modify the service to set -notification TRUE

**Comment by csuriano23** [comment]
I am trying the configuration switch in the production environment. I'll let you know in a few days.

Thank you

**Comment by csuriano23** [comment]
New configuration still has delay issues. Pool connections are not recycled, but sometimes during reset (when connection is returned to the pool) they take the standard 15 minutes before finalizing the rollback (SQLAlchemy logs `base.py: 505	INFO	ROLLBACK`). Maybe this is due to RAC interaction, even using events.

**Comment by csuriano23** [comment]
> What is your configuration now? 

Explicitly set up in creating/binding SQLAlchemy engine only:
```
pool_size=8
max_overflow=0
pool_recycle=-1
pool_timeout=30
events=True
autoflush=False
autocommit=False
```

> Have you tried adjusting TCP timeouts?

No, but I think it is one of the last things to try out in a production environment, since it is at OS-level (I don't know if Oracle have one specific). I can ask to sysadmins

> Do you have a non-SQLAlchemy testcase?

No, we always use SQLAlchemy as a connection broker. I can build an ad-hoc script, but unfortunately the issue doesn't happen regularly, so I don't know exactly how to replicate

**Comment by csuriano23** [comment]
> Would the connection close be doing a rollback? 

Not necessarily, we have cases for which it is doing a rollback and cases for which it doesn't

> The first thing any DB person will ask is how the DB service is configured.
> <...>
> Any sign the DB is stuck somewhere, e.g. on an archiver?
> I wonder what the impact of any sqlnet.ora parameters like `SQLNET.SEND_TIMEOUT` on a connection close is? I'll ask around.

Unfortunately DBAs/Sysadmins of the hosting company infastructure are not so responsive. Anyhow what you suggested is exactly what we are analyzing (TCP timeouts configs at OS and DB level, FAN settings, general failover architectural details, ...).

In the meanwhile I think it is difficult to reproduce the issue, since it seems to be strictly related to the peculiar customer DB solution.

Thank you for your support

**Comment by anthony-tuininga** [comment]
Closing - no activity
