### ISSUE TITLE
Cx_oracle not working for 12c conneciton

### ISSUE THREAD

**Issue by satish1573** [oracle/python-cx_Oracle#334]
1. What is your version of Python? Is it 32-bit or 64-bit?

2. What is your cx_Oracle version?
cx-oracle-7.2.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
import cx_Oracle

con = cx_Oracle.connect( 'XXX/XXXXX:1522/XXXX' )
cur = con.cursor( )
cur.execute( 'select sysdate  from dual' )

res = cur.fetchall( )
print
res

cur.close( )
con.close( )
4. What error(s) you are seeing?
Traceback (most recent call last):
  File "C:/Users/XXX/AppData/Local/Programs/Python/Python37-32/Lib/site-packages/cx_Oracle/__init__.py", line 10, in <module>
    from custom_exceptions import Warning, Error, InterfaceError, DatabaseError, DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\cx_Oracle\custom_exceptions.py", line 1, in <module>
    from utils import python3_or_better
  File "C:\Users\satishn\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\cx_Oracle\utils.py", line 31, in <module>
    cxString = unicode
NameError: name 'unicode' is not defined

5. What OS (and version) is Python executing on?
windows 10
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

7. What is your Oracle Database version?
12c

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by anthony-tuininga** [comment]
The traceback shows regular Python files. cx_Oracle is an extension built in C, so the file name should be cx_Oracle.pyd (or something similar to that). Python 3.x doesn't have a "unicode" object -- that is called "str" in Python 3.x. As such, whatever wrapper you appear to be using has a bug in it.

**Comment by cjbj** [comment]
@satish1573 here are the installation instructions: http://cx-oracle.readthedocs.io/en/latest/installation.html

**Comment by cjbj** [comment]
Closing due to inactivity
