### ISSUE TITLE
Support database connection string includes the TNS alias and the TNS_ADMIN connection property like JDBC Thin Driver

### ISSUE THREAD

**Issue by yuisong** [oracle/python-cx_Oracle#354]
Dose cx_Oracle support database connection string includes the TNS alias and the TNS_ADMIN connection property like JDBC Thin Driver dose?
For example:
`DB_URL="jdbc:oracle:thin:@dbname_high?TNS_ADMIN=/Users/test/wallet_dbname"`

If the answer is no, are you going to support this kind of connection? It is extremely useful when the same applications need to connect to ADWs or ATPs from different regions which cannot share the SSL connection properties in wallets. 

Reference: [JDBC Thin Connections and Wallets](https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/connect-jdbc-thin-wallet.html#GUID-5ED3C08C-1A84-4E5A-B07A-A5114951AA9E)

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
A: version 3.5.2, 64-bit
2. What is your cx_Oracle version?
A: version 6.4.1
5. What OS (and version) is Python executing on?
A: 4.14.35-1902.3.1.el7uek.x86_64
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
A:  yum install oracle-instantclient19.3-basic.x86_64 
7. What is your Oracle Database version?
A: Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production Version 18.4.0.0.0
8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
A: LD_LIBRARY_PATH=$ORACLE_HOME/lib; export LD_LIBRARY_PATH
9. What Oracle environment variables did you set?  How *exactly* did you set them?
ORACLE_HOME=/usr/lib/oracle/19.3/client64
export TNS_ADMIN=/adbt_blv/adbt/TNS
NLS_LANG=AMERICAN_AMERICA.UTF8

**Comment by anthony-tuininga** [comment]
As far as I understand there is no support for setting the TNS_ADMIN environment variable in a connect string. You can, of course, set that value prior to the first connection being made, but once the first connection is made, no further examination of that environment variable is ever performed.

To do what you want to do, however, I think 19c adds the support you require. See the [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/netag/configuring-naming-methods.html#GUID-E5358DEA-D619-4B7B-A799-3D2F802500F1). Note that you can set the location of the wallet as in something like the following:

```
conn = cx_Oracle.connect(dsn="mydbhost/myservice&wallet_location=”/Users/test/wallet_dbname”)
```

**Comment by yuisong** [comment]
I have a try, but get error.
>>> conn = cx_Oracle.connect("username", "password", dsn="adbt_high&wallet_location='/home/adbt/wallet_name'")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified

**Comment by cjbj** [comment]
"adbt_high" almost certainly needs to be something like "hostname/adbt_high" since this is Easy Connect syntax.

**Comment by yunqudev** [comment]
Seems cx_Oracle does not support two concurrent connection with different WALLET_LOCATION, anyway to workaround?
```

>>> import cx_Oracle
>>>
>>> db1 = cx_Oracle.connect("user1", "pass1", dsn="tcps://host1:1521/service1?SSL_SERVER_DN_MATCH=false&WALLET_LOCATION=/TNS1")
>>>
>>> db2 = cx_Oracle.connect("user2", "pass2", dsn="tcps://host2:1521/service1?SSL_SERVER_DN_MATCH=false&WALLET_LOCATION=/TNS2")

Traceback (most recent call last):
  File "<console>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-28860: Fatal SSL error
```

**Comment by dbsid** [comment]
I found cx_Oracle does not support concurrent connections with different WALLET_LOCATION, any workaround?

```
>>> import cx_Oracle
>>>
>>> db1 = cx_Oracle.connect("user1", "pass1", dsn="tcps://host1:1521/service1?SSL_SERVER_DN_MATCH=false&WALLET_LOCATION=/TNS1")
>>>
>>> db2 = cx_Oracle.connect("user2", "pass2", dsn="tcps://host2:1521/service1?SSL_SERVER_DN_MATCH=false&WALLET_LOCATION=/TNS2")

Traceback (most recent call last):
  File "<console>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-28860: Fatal SSL error
```

**Comment by cjbj** [comment]
I'll check with the network team.

**Comment by cjbj** [comment]
@dbsid this is a known limitation of the lower Oracle layer thaty is not specific to the Easy Connect Plus syntax.  The situation is being reviewed and cx_Oracle will automatically inherit any potential enhancement made in the Oracle libraries. For the moment, you will need to use different processes if you want to use multiple wallets.

**Comment by dbsid** [comment]
@cjbj Thanks, Please update the issue if any progress on the enhancement. We have a python application need to access ADW in different regions in the same process.

**Comment by cjbj** [comment]
@dbsid I'll make a note.

Since the behavior is not due to cx_Oracle, I'll close this issue.
