### ISSUE TITLE
cx_Oracle.NotSupportedError: Python value of type method not supported.

### ISSUE THREAD

**Issue by shivsuryaking** [oracle/python-cx_Oracle#358]
the connection code is:-
```
dsn_tns=cxo.makedsn('localhost', '1521', service_name='orcl') 
    conn=cxo.connect(user=r'system', password='bagal123', dsn=dsn_tns) 
    cur=conn.cursor()
    statement = 'insert into vai(s_f_name,s_l_name,,s_e_mail,s_age,s_h_address,s_s_name,s_s_address,s_std,s_stream,s_contact) values (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10)'
    cur.execute(statement, ( v.get(), v1.get() , v2.get(), v3.get(), v4.get(), v5.get() , v6.get() , v7.get() , v8.get , v9.get()))
    conn.commit()
```

the remaining code main part : -
```
Label(w,text="Scholarship Application",bg="gold").grid(row=1,column=2)
Label(w,text="FIRST NAME",bg="gold").grid(row=3,column=1)
v=StringVar()
Entry(w,textvariable=v).grid(row=3,column=2)
Label(w,text="LAST NAME",bg="gold").grid(row=3,column=3)
v1=StringVar()
Entry(w,textvariable=v1).grid(row=3,column=4)
Label(w,text="E_MAIL",bg="gold").grid(row=5,column=1)
v2=StringVar()
Entry(w,textvariable=v2).grid(row=5,column=2)
Label(w,text="AGE",bg="gold").grid(row=7,column=1)
v3=IntVar()
Entry(w,textvariable=v3).grid(row=7,column=2)
Label(w,text="HOME ADDRESS",bg="gold").grid(row=9,column=1)
v4=StringVar()
Entry(w,textvariable=v4).grid(row=9,column=2)
Label(w,text="SCHOOL NAME",bg="gold").grid(row=11,column=1)
v5=StringVar()
Entry(w,textvariable=v5).grid(row=11,column=2)
Label(w,text="SCHOOL ADDRESS",bg="gold").grid(row=11,column=3)
v6=StringVar()
Entry(w,textvariable=v6).grid(row=11,column=4)
t=("1","2","3","4","5","6","7","8","9","10")
Label(w,text="STANDARD",bg="gold").grid(row=13,column=1)
v7=StringVar()
Spinbox(w,value=t,textvariable=v7).grid(row=13,column=2)
t=("COMMERS","SCIENCE","ART")
Label(w,text="STREAM",bg="gold").grid(row=13,column=3)
v8=StringVar()
Spinbox(w,value=t,textvariable=v8).grid(row=13,column=4)
Label(w,text="contact",bg="gold").grid(row=15,column=1)
v9=Var()
Entry(w,textvariable=v9).grid(row=15,column=2)
```

what is wrong here can please you help me to solve this 
the error is as following: -
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\adimpc\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\adimpc\Desktop\vaishnavi.py", line 36, in save
    cur.execute(statement, ( v.get(), v1.get() , v2.get(), v3.get(), v4.get(), v5.get() , v6.get() , v7.get() , v8.get , v9.get()))
cx_Oracle.NotSupportedError: Python value of type method not supported.
```

**Comment by cjbj** [comment]
It would help us if you formatted code using https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by anthony-tuininga** [comment]
Looks like you have a typo. ``v8.get`` is a function. You probably need to call it to get the value instead by using ``v8.get()``.

**Comment by anthony-tuininga** [comment]
I assume that my response resolved your issue. If not, let me know!
