### ISSUE TITLE
"cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library error" after Windows 10 upgrade

### ISSUE THREAD

**Issue by shankarps** [oracle/python-cx_Oracle#362]
I had a running setup in Windows 7. I upgraded my laptop to Windows 10 and then setup the PATH variable to the Oracle instant client. But I am now getting the same error. Can anyone please check and help?
#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:13:57) [MSC v.1916 64 bit (AMD64)] on win32

2. What is your cx_Oracle version?
Version: 7.2.2

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?

`Traceback (most recent call last):
  File ".\used_car_reader.py", line 14, in <module>
    connection = cx_Oracle.connect("readman", "readusedcar", "cdcodb2.internetbrands.com:1521/pusdcar.internetbrands.com")
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help`

5. What OS (and version) is Python executing on?

Windows 10 (64 bit)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

Basic Light Client Shared Library 64-bit - 19.3.0.0.0

7. What is your Oracle Database version?
Oracle 11

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk1.8.0_221\bin;C:\exe\apache-maven-2.2.1\bin;C:\exe\instantclient_19_3;C:\exe\OracleInstantclient_19_3;

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Python script that immediately runs to show us the problem?

Here is the code:

```
import cx_Oracle

import os
import platform

LOCATION = r"C:\exe\OracleInstantclient_19_3"
print("ARCH:", platform.architecture())
print("FILES AT LOCATION:")
for name in os.listdir(LOCATION):
    print(name)
os.environ["PATH"] = LOCATION + ";" + os.environ["PATH"]


connection = cx_Oracle.connect("user", "pwd", "DB URL")

cursor = connection.cursor()
```

**Comment by anthony-tuininga** [comment]
It looks like you have done everything right -- in that you have everything 64-bit (Python, cx_Oracle, Oracle client libraries). Did you make sure you have the right redistributable in place? See the link provided in the error message if you're not sure which one you need. You can also use ``depends.exe`` or an equivalent in order to determine which dependencies are missing. Finally, set the ``PATH`` environment variable outside of your Python script and simply verify that it is set by examining the contents of that environment variable in you script -- just to be absolutely sure that everything is as you expect.

**Comment by shankarps** [comment]
Thanks. I verified that the PATH is set correctly. I am also sure that the Oracle client Library I have is the right version.
Is there a way to enable debug mode to see where the cx_Oracle is looking for the Oracle Client Library? Or can I hard code the library location, instead of letting it use the PATH?

**Comment by anthony-tuininga** [comment]
Currently there is no way to identify where cx_Oracle is looking for oci.dll -- unless you put it in the same directory as cx_Oracle.pyd itself; otherwise, Windows uses its [standard library search order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order?redirectedfrom=MSDN) noted in the documentation linked to in the error itself. You can, of course, manipulate the code in the function ``dpiOci__loadLibOnWindows()`` found in the ``odpi/src`` subdirectory to hard-code a full path to your library of choice -- to see if that corrects the issue. I'd suggest using ``depends.exe`` or an equivalent to determine if there are any other issues -- since I believe Windows doesn't differentiate between "I can't find the DLL" and "I found the DLL but I couldn't load it".

**Comment by shankarps** [comment]
@anthony-tuininga You were right. I checked the oci.dll using "Dependency Walker". I can see a number of API-MS-WIN-CORE* files missing or could not be opened.
Is this because of Microsoft Visual Studio 2017 Redistributable? I have already installed Visual Studio from here. https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
[oci.txt](https://github.com/oracle/python-cx_Oracle/files/3655128/oci.txt)

**Comment by anthony-tuininga** [comment]
@shankarps, I do not use Windows on a regular basis (I use Linux instead) so cannot answer your questions in detail. For instant client 19.3 you need the Visual Studio 2017 redistributable installed. If you have already installed it, then I'm not sure what the problem can be. I did a quick Google search for those files being missing and there were a number of suggestions given -- but not being a Windows user I'm not sure how relevant they are! If you find out what the problem is, let us know so we can update our documentation accordingly. Thanks!

**Comment by sharman123** [comment]
I'm running into same issue. spent the whole day trying to figure it out. won't work. on my other pc it worked just fine. here is the test that I ran that someone had suggested to troubleshoot on some other site.
import os
import platform

LOCATION = r"C:\oracleinstantclient_19_3"
print("ARCH:", platform.architecture())
print("FILES AT LOCATION:")
for name in os.listdir(LOCATION):
    print(name)
os.environ["PATH"] = LOCATION + ";" + os.environ["PATH"]

import cx_Oracle
conn = cx_Oracle.connect("USER/pass@server/SERVICE")

here is the response (it clearly lists the path):
ARCH: ('64bit', 'WindowsPE')
FILES AT LOCATION:
adrci.exe
adrci.sym
BASIC_LICENSE
BASIC_README
genezi.exe
genezi.sym
oci.dll
oci.sym
ocijdbc19.dll
ocijdbc19.sym
ociw32.dll
ociw32.sym
ojdbc8.jar
oramysql19.dll
oramysql19.sym
orannzsbb19.dll
orannzsbb19.sym
oraocci19.dll
oraocci19.sym
oraocci19d.dll
oraocci19d.sym
oraociei19.dll
oraociei19.sym
oraons.dll
orasql19.dll
orasql19.sym
ucp.jar
uidrvci.exe
uidrvci.sym
vc14
xstreams.jar
Traceback (most recent call last):
  File "myscriptTest.py", line 21, in <module>
    conn = cx_Oracle.connect("USER/pass@server/SERVICE")
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help

**Comment by cjbj** [comment]
What VS resdistributable did you install?

What's different about your other computer?

Run `dumpbin /headers oci.dll` in C:\oracleinstantclient_19_3.

Also you may want to verify that it's ok to set PATH after the executable starts.  I thought it was ok, but not being a Windows user I cannot confirm.  It's definitely NOT ok to do this on Linux.

**Comment by sharman123** [comment]
thanks for quick response. 
VS 2015-2019 redistributable (x64) 
other computer is microsoft surface. doesn't have that many softwares installed as this one. also that pc somehow required me to install 32 bit oracleclient, I believe there python is running on 32 bit.
Run dumpbin /headers oci gives me 'dumpbin' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cjbj** [comment]
dumpbin is likely something you have to install.

Keep digging into it: try setting PATH before running Python, try an older Oracle client etc.

**Comment by anthony-tuininga** [comment]
Closing - no activity

**Comment by Amiyamails** [comment]
I could solve this error. Below in summary:
I was getting below Error:
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: 
C:\Oracle\product\10.1.0\Client_1\bin\oci.dll

Solution steps:
https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html
1. Downloaded oracle instant client (recent version) from above URL
2. unzip the file
3. set the PATH like below
set PATH=%PATH%;E:\PYTHON\PDBC\instantclient_19_5\
4. connection is successful now.

**Comment by cjbj** [comment]
For reference, the install instructions are in https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html
