### ISSUE TITLE
Connecting to AWS Oracle RDS using cx_Oracle over SSL

### ISSUE THREAD

**Issue by sulabhk** [oracle/python-cx_Oracle#417]
1. Review the [cx_Oracle Documentation](https://cx-oracle.readthedocs.io/en/latest/index.html).  Output Log:
Traceback (most recent call last):
  File "ssl_test.py", line 16, in <module>
    con = cx_Oracle.connect("hash", "hash", dsn)
cx_Oracle.DatabaseError: ORA-28759: failure to open file

Error: 
cx_Oracle.DatabaseError: ORA-28759: failure to open file

2. Describe the problem
Trying to establish connectivity via SSL to an Oracle RDS instance
Attempting to connect to a non-SSL Oracle instance works fine.
Referred to https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#optional-oracle-net-configuration-files, but it doesn't talk about how to generate and where to place the wallet file required for SSL, perhaps the error is an attempt to search for that file!

3. Include a runnable Python script that shows the problem.  
No sql script required as such.

4. Platform and cx_Oracle version info:

platform.platform: 'Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic')
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
('sys.maxsize > 2**32:', True)
platform.python_version: '2.7.17'

And:
cx_Oracle.version: '7.3.0'
cx_Oracle.clientversion: 12, 1, 0, 2, 0

5. What is your Oracle Database version?
AWS RDS
DB Engine : Oracle Standard Edition Two
Engine version:  12.1.0.2.v12
-- | --

**Comment by sulabhk** [comment]
Created an auto-login wallet using
`orapki wallet create -wallet _wallet_directory_ -auto_login_only`
 and place under the wallet directory and get a different error now, not sure how good that is a progress!
`traceback (most recent call last):
  File "ssl_test.py", line 16, in <module>
    con = cx_Oracle.connect("ax_admin", "admin_12345", dsn)
cx_Oracle.DatabaseError: ORA-28788: user provided invalid information, or an unknown error`

**Comment by cjbj** [comment]
Closing - no activity.
