### ISSUE TITLE
Test oracle 19c AC get ORA-41412: results changed during replay; failover cannot continue

### ISSUE THREAD

**Issue by ltwell** [oracle/python-cx_Oracle#445]
1. Describe the problem
I want use python to test oracle 19c AC feature,I got the error output as 
```
python3 Mytest1.py 
all done!
begin
You are Connected to RAC Instance - o19t22
GUID a69d64e2e3cbd2b9e0532002020a6af3
Traceback (most recent call last):
  File "Mytest1.py", line 62, in <module>
    Query1()
  File "Mytest1.py", line 45, in Query1
    for result2 in cursor.execute(sql1):
cx_Oracle.DatabaseError: ORA-41412: results changed during replay; failover cannot continue

```

2. the python script as 
```
# ------------------------------------------------------------------------------
# Mytest1.py
# ------------------------------------------------------------------------------
import time
import cx_Oracle
import SampleEnv

# pool = cx_Oracle.SessionPool(SampleEnv.GetMainUser(),
#         SampleEnv.GetMainPassword(), SampleEnv.GetConnectString(), min=2,
#         max=5, increment=1, threaded=True)
conn = cx_Oracle.connect(SampleEnv.GetMainConnectString())


def Query1():
    conn.autocommit = False
    cursor = conn.cursor()
    print("begin")
    sql1 = """
               select instance_name from v$instance 
            """
    for result in cursor.execute(sql1):
        print('You are Connected to RAC Instance - %s' % result)
    sql2 = """
            select sys_guid() from dual
            """
    for result in cursor.execute(sql2):
        for index in range(len(result)):
            print('GUID %s' % result[index].hex())
    sql3 = """
            alter session set nls_date_format='yyyymmdd hh24miss'
            """
    cursor.execute(sql3)
    sql4 = """
            insert into test1 values(1)
            """
    cursor.execute(sql4)
    sql5 = """
            insert into test2 values(sys_guid())
            """
    cursor.execute(sql5)
    time.sleep(10)
    # at this time the instance which connect shutdown abort

    for result2 in cursor.execute(sql1):
        print('You are Connected to RAC Instance - %s' % result2)
    sql6 = """
            select value from v$nls_parameters where parameter='NLS_DATE_FORMAT'
            """
    for result3 in cursor.execute(sql6):
        for index in range(len(result3)):
            print('NLS_DATE_FORMAT %s' % result3[index])

    for result4 in cursor.execute(sql2):
        for index in range(len(result4)):
            print('GUID %s' % result4[index].hex())
    conn.commit()

Query1()

```
the test1 and test2 table created as 
```
create table test1 (id int);
create table test2 (id raw(16));
```
In SampleEnv.py Parameters as
```
PARAMETERS = {"MAIN_USER": "pythondemo", "MAIN_PASSWORD": "oracle", "CONNECT_STRING": "10.2.2.35/ac"}

```
the ac service config as
```
srvctl config service -d o19t2 -s ac
Service name: ac
Server pool: 
Cardinality: 2
Service role: PRIMARY
Management policy: AUTOMATIC
DTP transaction: false
AQ HA notifications: true
Global: false
Commit Outcome: true
Failover type: TRANSACTION
Failover method: BASIC
Failover retries: 30
Failover delay: 3
Failover restore: LEVEL1
Connection Load Balancing Goal: LONG
Runtime Load Balancing Goal: NONE
TAF policy specification: NONE
Edition: 
Pluggable database name: 
Hub service: 
Maximum lag time: ANY
SQL Translation Profile: 
Retention: 604800 seconds
Replay Initiation Time: 300 seconds
Drain timeout: 
Stop option: 
Session State Consistency: DYNAMIC
GSM Flags: 0
Service is enabled
Preferred instances: o19t21,o19t22
Available instances: 
CSS critical: no
Service uses Java: false
```
I also execute GRANT  KEEP SYSGUID TO pythondemo

3. Show the output of:

```
>>> import sys
>>> import platform
>>> 
>>> print("platform.platform:", platform.platform())
platform.platform: Linux-5.4.0-31-generic-x86_64-with-glibc2.29
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.8.2
>>> import cx_Oracle
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 7.3.0
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

```

4. What is your Oracle Database version?
Oracle 19.6 RAC

**Comment by cjbj** [comment]
Your `select instance_name from v$instance` will likely return a different value during the replay to the 2nd instance.

Although not good as being there, you may find a few useful things in the conference slides [Application High Availability Best Practices and New Features](https://static.rainfocus.com/oracle/oow19/sess/1553544864828001ZiKm/PF/DEV4613-Application-High-Availability-Best-Practices-and-New-Features_1569021691438001iiZh.pdf).

**Comment by ltwell** [comment]
when I delete the sql ' select instance_name from v$instance',the script  can run no error ,I want to know if it is a clause to indicate which sql can be replay like in java i can use ((oracle.jdbc.replay.ReplayableConnection)conn).beginRequest() and ((oracle.jdbc.replay.ReplayableConnection)conn).endRequest() to protect the replayable code

**Comment by cjbj** [comment]
When using a connection (aka session) pool the aquire/close does the same thing and marks the boundaries for AC.  And if you aren't using a cx_Oracle connection pool you can use TAC instead of AC.

Here's a good whitepaper that may be useful: [Continuous Availability: Application Continuity for the Oracle Database](https://www.oracle.com/technetwork/database/options/clustering/applicationcontinuity/adb-continuousavailability-5169724.pdf).  There's a (slightly hard to read) table there saying which technology to use.

**Comment by ltwell** [comment]
OK ,I got it
