### ISSUE TITLE
cursor.execute() hangs on a statement without propagating ORA-01652

### ISSUE THREAD

**Issue by concretevitamin** [oracle/python-cx_Oracle#559]
**1. What versions are you using?**

Client:
```
platform.platform: Linux-5.4.0-1034-azure-x86_64-with-debian-buster-sid
sys.maxsize > 2**32: True
platform.python_version: 3.7.7
cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (21, 1, 0, 0, 0)
```
Server: 
```
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
```
**2. Is it an error or a hang or a crash?**

Hang.

**3. What error(s) or behavior you are seeing?**

tldr: `cursor.execute()` hangs on an expensive statement without any exceptions raised, even after the execution has been  killed by the server.

I've a weird statement that's pretty expensive.  Entering this SQL statement in sqlplus eventually leads to this error:

    ERROR at line 1:
    ORA-01652: unable to extend temp segment by 128 in tablespace TEMP

This is expected & good.  

However, using cx_Oracle, specifically using 

    cursor.execute(same_statement)

would result in the same amount of work being done, and at some point the CPU utilization on the server stopped.  `top` showed the execution process on the server got created, started to have utilization, then later got killed.  This meant ORA-01652 has happened.  However, the cursor.execute(...) call stays blocked without raising an exception.  This makes the app stay in a stuck state.  At that point it doesn't respond to Ctrl-C SIGINT.

What's wrong?  Is it possible to enable an exception to be raised?  

**What I've tried**

(a) Setting `DPI_DEBUG_LEVEL` to 15:
```python
...
c.execute(sql) 
# The above call prompted these messages:
ODPI [84562] 2021-05-03 17:04:34.196: fn start dpiConn_prepareStmt(0x563b2b7115a0)
ODPI [84562] 2021-05-03 17:04:34.196: ref 0x563b2b78a050 (dpiStmt) -> 1 [NEW]
ODPI [84562] 2021-05-03 17:04:34.196: ref 0x563b2b7115a0 (dpiConn) -> 2
ODPI [84562] 2021-05-03 17:04:34.197: fn end dpiConn_prepareStmt(0x563b2b7115a0) -> 0
ODPI [84562] 2021-05-03 17:04:34.197: fn start dpiStmt_getInfo(0x563b2b78a050)
ODPI [84562] 2021-05-03 17:04:34.197: fn end dpiStmt_getInfo(0x563b2b78a050) -> 0
ODPI [84562] 2021-05-03 17:04:34.197: fn start dpiStmt_setFetchArraySize(0x563b2b78a050)
ODPI [84562] 2021-05-03 17:04:34.197: fn end dpiStmt_setFetchArraySize(0x563b2b78a050) -> 0
ODPI [84562] 2021-05-03 17:04:34.197: fn start dpiStmt_execute(0x563b2b78a050)
```
After the executor process on the server is killed, this call starts hanging.  No further messages are printed.

(b) Setting `?ENABLE=BROKEN` in the `connect()` call:
```python
connection = cx_Oracle.connect('sys/pw@host/sid?ENABLE=BROKEN', mode=cx_Oracle.SYSDBA)
```
After around 2+ hours or so (from what I read, this seems related to tcp keepalive on the client side), the following is printed and the connection/cursor objects become closed:
```python
>>> c.execute(sql)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel
Process ID: 23097
Session ID: 498 Serial number: 31754

>>> connection.ping()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.OperationalError: ORA-03114: not connected to ORACLE
```

**4. Include a runnable Python script that shows the problem.**

Not sure how to reproduce ORA-01652 synthetically.  However, this is all that's being done:
```python
import cx_Oracle
connection = cx_Oracle.connect('sys/pw@host/sid', mode=cx_Oracle.SYSDBA)
c = connection.cursor()
sql = """<SELECT statement>"""
c.execute(sql)  # Hangs.
```

**Comment by concretevitamin** [comment]
Tried using `connection.callTimeout`, no timeout kicked in.  It appears as if the connection got killed unilaterally on the server side without triggering an error on the client.

**Comment by suraj-ora-2020** [comment]
How does the client stack/pstack <pid of client> trace look when the server CPU usage stops.Could you please verify.

**Comment by suraj-ora-2020** [comment]
2 - Could you please verify whether  the connect string is similar to what has been used with sqlplus because there are some behaviour changes when you use mode as sysdba.
connection = cx_Oracle.connect("username", password, "hostname/servicename").
Note the changes with change in connect string.

**Comment by cjbj** [comment]
@concretevitamin where is this at?  Did you manage to get the requested information?

**Comment by concretevitamin** [comment]
@cjbj @suraj-ora-2020 Thanks. I believe I've provided sufficiently detailed info for a reproduction.  (RE Q2: the connect strings are the same in Python and in sqlplus; see the bottom most Python snippet.)  Unfortunately won't have bandwidth to try out stack/pstack (is this needed even with knowing it gets stuck at `dpiStmt_execute()`?).  

Had to work around this problem using user-level timeout.  Feel free to close this if there isn't interest to reproduce.

**Comment by WilliamStam** [comment]
hi @concretevitamin , what do you mean by "'user-level timeout". im also having timeout issues where the timeout isnt honored. looking for all the different ways to force a timeout.

**Comment by cjbj** [comment]
@WilliamStam open a new issue and give details about what you trying.

**Comment by cjbj** [comment]
@concretevitamin I'm interested in helping, but from experience I know that without your exact test case, I could end up looking at completely unrelated things.  Maybe it's your exact statement that is tickling some layer of code that isn't propagating what we expect.  Did you try without SYSDBA in cx_Oracle, as @suraj-ora-2020 mentioned?  Both SQL*Plus and cx_Oracle use the exact same Oracle Client libraries so I'd expect similar behaviors for timeouts and DB errors.

**Comment by avatarofhope2** [comment]
I am seeing similar behavior.

1. run heavy select query
2. oracle dba says query completes successfully
3. cx_oracle hangs permanently (> 24 hours)

We are waiting for packet trace on server side to see if it is network related, but I would expect cx_oracle to detect the closed connection.

**Comment by pax0r** [comment]
I have observed a similar issue at my app. I am not using SYSDBA mode. In my case this is web app hosted with uwsgi. One in some queries hangs until uwsgi kills worker (I have Harakiri mode enabled, which kill the process if it won't respond in 120 seconds).

**Comment by cjbj** [comment]
Perhaps the TCP layer doesn't timeout?  If so, then cx_Oracle won't get control back.  Try a client sqlnet.ora RECV_TIMEOUT, see https://cx-oracle.readthedocs.io/en/latest/user_guide/ha.html#network-configuration

**Comment by cjbj** [comment]
Closing this due to inactivity.  The various issues mentioned may or may not be unrelated.  Please open new issues if new testcases are discovered.
